name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build -x test
        
      - name: Build and Push Docker Image
        run: |
          docker build -t mindit-backend-image .
          docker save mindit-backend-image > mindit-backend-image.tar
          
      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "mindit-backend-image.tar"
          target: "/home/${{ secrets.EC2_USERNAME }}"
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop mindit-backend-container || true
            docker rm mindit-backend-container || true
            docker rmi mindit-backend-image || true
            
            rm -f mindit-backend-image.tar
            
            docker load < mindit-backend-image.tar
            docker run -d \
              -p 8088:8088 \
              --name mindit-backend-container \
              mindit-backend-image
